version: '2'
volumes:
  wordpressdata: {}
  certdata: {}
  wordpressdbdata: {}
services:
  #docker_s3_backup:
  #  build: docker-backup-to-s3
  #  env_file:
  #    - ./s3_backup.env
  #  volumes:
  #    - baikaldata:/data/baikal
  #  depends_on:
  #    - baikal
  haproxy:
    build: docker-haproxy/
    volumes:
      - certdata:/etc/letsencrypt/live
    expose:
      - "80"
      - "443"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    links:
      - wordpress
    #depends_on:
    #  - simp_le
    restart: always
  #simp_le:
  #    image: m3adow/letsencrypt-simp_le
  #    expose:
  #      - "80"
  #    ports:
  #      - "80:80"
  #    # restart: always
  #    volumes:
  #      - certdata:/certs
  #    command:  '-f account_key.json  -f full.pem --email foo@bar.de -d bar.de'
  db:
    image: mysql:5.7
    volumes:
      - wordpressdbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    expose:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_USER: wordpress 
